### ISSUE TITLE
Countdown timer for Vexamus' Arcane Expulsion spell in Algeth'ar Academy is off

### ISSUE THREAD

**Issue by Eldranil** [BigWigsMods/LittleWigs#865] opened 2023-01-08 20:57 UTC
## Describe the problem
The countdown timer for Vexamus' frontal ability in Algeth'ar Academy is off after the first one.

### What steps will reproduce the problem?

1.  Toggle on the countdown timer for Arcane Expulsion on Vexamus in Algeth'ar Academy.
2.  Pull the boss.
3.  Compare the countdown information to the actual cast of the boss. After the first cast, the accuracy drifts away until it is completely off.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
Not applicable.

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
Version 10.0.22.

### Do you have an error log of what happened?
Not applicable.

### Any additional information? (example: WoW language if not English)
I observed this bug on every pull consistently, including a pull yesterday on M+ (07 Jan 2023) and on normal today as a solo tank for testing (08 Jan 2023).

This is the spell in question
https://www.wowhead.com/spell=385958/arcane-expulsion

**Comment by ntowle** [comment] 2023-01-08 21:53
This spell isn't cast on a consistent timer unfortunately, so exact cast times will vary from pull to pull. In general timers which are approximate will have their times denoted with a ~ before the number.

That said I did several pulls between Mythic and Normal on this today and the minimum CD was 23.1 which both matches the minimum CD I can find in public logs and my own logs from Season 1. The maximum time between casts was 30.4. The previous minimum CD was from beta where I observed 19.4 both in heroic and mythic+. So seems like this spell's CD was increased slightly between then and now. There doesn't seem to be a consistent pattern for when or why the spell may be delayed, I suspect it's just spell queuing with higher priority abilities this boss casts.

I'll update the timer to 23.1 from 19.4. Thanks for reporting.

Here's the observed timers from my pulls today for reference:

Normal:
- pull:12.3, 23.1, 26.7, 26.8, 23.1, 26.7, 23.1, 30.3, 23.2

Mythic:
- pull:12.2, 26.3, 26.8, 27.2, 30.4, 23.1, 26.3
- pull:12.2, 26.7, 26.7, 30.4, 23.1, 26.2, 29.7, 26.8, 30.4, 23.0

**Comment by ntowle** [comment] 2023-01-08 21:55
Fixed by 5e889ed2.

**Closed by ntowle** 2023-01-08 21:55 UTC
Labels: retail

**Comment by ntowle** [comment] 2023-01-08 23:28
From reviewing logs a bit further it looks like the longer CDs are caused by Arcane Fissure casts, which adds ~3.6 seconds to all other CDs per Arcane Fissure cast.

Updated timers to reflect this in https://github.com/BigWigsMods/LittleWigs/commit/abb54c3994e9336e0d66e5cc50ae4be989fdd07b.
