### ISSUE TITLE
Doesn't show trash ability bars

### ISSUE THREAD

**Issue by narmiaa1** [BigWigsMods/LittleWigs#985] opened 2023-12-30 16:27 UTC
## Describe the problem
Hi. LittleWigs does not show the cooldown bars for trash in dungeons. I can see them show for other players on streams but it won't for me. I have to use WA or DBM to fill the gaps.

### What steps will reproduce the problem?

1.  Uninstall
2.  Reinstall

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
10.2.28

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English)
My game is in french

**Comment by ntowle** [comment] 2023-12-30 17:06
It's not a bug, there are only trash cooldown bars for a few mobs at the moment - usually just the unique mini-bosses. An example would be Gnarlroot in Everbloom. So there's likely nothing wrong with your installation.

**Comment by Nicklastoft** [comment] 2024-05-15 19:18
I can confirm this bug is a thing.
For example, the final miniboss in ruby life pools, my healer swears he used his bar from big/littlewigs to preramp the aoe storm, and now we cant force that bar to show, no matter what we try (it is ofc set to show in the settings etc)

i have the same issue myself, and it turned up in the last week or so.

we tried uninstalling, deleting all WTF files related to bigwigs, not loading every other addon.
Should be relatively easy to replicate the issue, as the bar just simply wont show up

**Comment by funkydude** [comment] 2024-08-09 18:13
This is something you will start seeing with the new expansion onwards, closing as resolved.

**Closed by funkydude** 2024-08-09 18:13 UTC
Labels: retail
