### ISSUE TITLE
Lua errors (bad argument #2 to 'format')

### ISSUE THREAD

**Issue by spamwax** [BigWigsMods/LittleWigs#1130] opened 2024-08-19 04:29 UTC
## Describe the problem
Lua errors (on Beta) in Necrotic Wake

### What steps will reproduce the problem?

1. Enter Necrotic Wake
2. Fight trash mobs after the 1st boss (up the stairs)
3. Get the error!

### What version of LittleWigs are you using? (Stating 'latest' is not useful)
11.0.12

### Do you have an error log of what happened?
```lua
12x ...Ons/LittleWigs_Shadowlands/TheNecroticWake/Trash.lua:384: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@LittleWigs_Shadowlands/TheNecroticWake/Trash.lua"]:384: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:735: in function <BigWigs_Core/BossPrototype.lua:693>

Locals:
(*temporary) = "%s on %s"
(*temporary) = "Boneshatter Shield"
(*temporary) = nil
(*temporary) = "string expected, got nil"
```

### Any additional information? (example: WoW language if not English)
Output of `GetBuildInfo()`
11.0.2, 5610, Aug 12 2024, 110002

**Comment by funkydude** [comment] 2024-08-19 04:42
Duplicate of #1127

**Closed by funkydude** 2024-08-19 04:42 UTC
Labels: retail
